const routesConfig = {
  login: "/login",
  register: "/register",
  checkEmail: "/register/check-email",
  home: "/",
  searchResults: "/searchresults",
  hotelDetails: "/hotel",

  join: "/join",
  becomeAHostCategory: "/join/become-a-host/category",
  becomeAHostProperty: "/join/become-a-host/property",
  becomeAHostOwner: "/join/become-a-host/owner",
  becomeAHostFeedBack: "/join/become-a-host/feedback",
  becomeAHostAddRess: "/join/become-a-host/address",
  becomeAHostMap: "/join/become-a-host/map",
  becomeAHostHotelName: "/join/become-a-host/name",
  becomeAHostFacilities: "/join/become-a-host/facilities",
  becomeAHostHouseRules: "/join/become-a-host/house-rules",
  becomeAHostOverviewRoom: "/join/become-a-host/overview-room",
  becomeAHostAddRoom: "/join/become-a-host/add-room",
  becomeAHostBathRoom: "/join/become-a-host/bathroom-details",
  becomeAHostAmenities: "/join/become-a-host/unit-amenities",
  becomeAHostUnitName: "/join/become-a-host/unit-name",
  becomeAHostHotelPrice: "/join/become-a-host/price",
  becomeAHostHotelPriceOverview: "/join/become-a-host/price-overview",
  becomeAHostHotelGroupDiscount: "/join/become-a-host/group-discount",
  becomeAHostHotelPolicy: "/join/become-a-host/policies",
  becomeAHostNonRefundable: "/join/become-a-host/non-refundable",
  becomeAHostCalendarSync: "/join/become-a-host/calendar-sync",
  becomeAHostPaymentMode: "/join/become-a-host/payment-mode",
  becomeAHostInvoicing: "/join/become-a-host/invoicing",
  becomeAHostPartner: "/join/become-a-host/know-your-partner",
  becomeAHostPhoto: "/join/become-a-host/photo",
};

export default routesConfig;
