const routesConfig = {
  login: "/login",
  register: "/register",
  contactDetails: "/register/contact-details",
  registerPassword: "/register/password",
  forgotPassword: "/forgot-password",
  forgotConfirmation: "/forgot-password/confirmation",
  checkEmail: "/register/check-email",

  home: "/",
  becomeAHostCategory: "/become-a-host/category",
  becomeAHostProperty: "/become-a-host/property",
  becomeAHostOwner: "/become-a-host/owner",
  becomeAHostFeedBack: "/become-a-host/feedback",
  becomeAHostAddRess: "/become-a-host/address",
  becomeAHostMap: "/become-a-host/map",
  becomeAHostHotelName: "/become-a-host/name",
  becomeAHostFacilities: "/become-a-host/facilities",
  becomeAHostHouseRules: "/become-a-host/house-rules",
  becomeAHostOverviewRoom: "/become-a-host/overview-room",
  becomeAHostAddRoom: "/become-a-host/add-room",
  becomeAHostBathRoom: "/become-a-host/bathroom-details",
  becomeAHostAmenities: "/become-a-host/unit-amenities",
  becomeAHostUnitName: "/become-a-host/unit-name",
  becomeAHostHotelPrice: "/become-a-host/price",
  becomeAHostHotelPriceOverview: "/become-a-host/price-overview",
  becomeAHostHotelGroupDiscount: "/become-a-host/group-discount",
  becomeAHostHotelPolicy: "/become-a-host/policies",
  becomeAHostNonRefundable: "/become-a-host/non-refundable",
  becomeAHostCalendarSync: "/become-a-host/calendar-sync",
  becomeAHostPaymentMode: "/become-a-host/payment-mode",
  becomeAHostInvoicing: "/become-a-host/invoicing",
  becomeAHostPartner: "/become-a-host/know-your-partner",
  becomeAHostPhoto: "/become-a-host/photo",
};

export default routesConfig;
